version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  commit-message:
    prefix: "patch"
    prefix-development: "build"
    include: "scope"
  schedule:
    interval: weekly
    day: friday
    time: "17:00"
    timezone: America/New_York
  open-pull-requests-limit: 10
  reviewers:
  - davidlday
