output-format: grouped

strictness: medium
test-warnings: false
# docs will be cleaned in a subsequent branch
doc-warnings: false
member-warnings: true
inherits:
  - default
ignore-paths:
  - build
  - dist
# ignore-patterns:
#   - (^|/)skip(this)?(/|$)
autodetect: true
max-line-length: 88

pep257:
  disable:
    - D211
    - D212

pylint:
  run: true
  disable:
    - missing-module-docstring
    - too-many-arguments

pyflakes:
  run: false
