# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python Lint

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      # - name: Set up Python 3.x
      #   uses: actions/setup-python@v2
      #   with:
      #     python-version: "3.x"
      # - name: Install dependencies
      #   run: |
      #     pip install --upgrade pip
      #     pip install pylint black
      #     pip install .
      - name: Python Linting
        uses: ricardochaves/python-lint@v1.4.0
        with:
          python-root-list: "prosegrinder setup.py"
          use-pylint: true
          use-pycodestyle: false
          use-flake8: false
          use-black: true
          use-mypy: false
          use-isort: true
          extra-pylint-options: ""
          extra-pycodestyle-options: ""
          extra-flake8-options: ""
          extra-black-options: ""
          extra-mypy-options: ""
          extra-isort-options: ""
      # - name: Install build dependencies
      #   run: |
      #     pip install --upgrade pip setuptools wheel
      # - name: Install module & dependencies
      #   run: |
      #     python ./setup.py install
      # - name: Lint with Prospector
      #   uses: jpetrucciani/prospector-check@1.3.1
      #   with:
      #     path: .
